DudeAlex/AlexFall2024

src/test/java/FirstTest.java
=> Iryna h testClickOnStoreButtonAdded

src/test/java/FirstTest.java
=> add testKet

src/test/java/FirstTest.java
Added test for add featured product to cart
=> add testFeaturedProductAddToCart

src/test/java/FirstTest.java, src/test/java/ItemTest.java
Move my tests to ItemTest, add data provider for them, add testSortByPriceHighToLow
=> Add data provider

src/test/java/FirstTest.java
=> Test sorting order desc

src/test/java/FirstTest.java, src/test/java/ItemTest.java
Удалила тесты , которые видимо кто-то по ошибке вернул в результате решения конфликта 
Тест находит баг, на мой взгляд , пока оставляю его с комментом и буду изучать как оформить  и  надеюсь на мнение со стороны
=> Add testVerifyItemsCorrespondentCategories

src/test/java/FirstTest.java
Дописала тест по сортировке (свой вариант)
=> Add_testEDSortByPriceHighToLow___complete_sorting

src/test/java/NavigationMenuTest.java
https://app.clickup.com/t/8689q888u
=> Add NavigationMenuTests

src/test/java/FirstTest.java
The number of items in the cart is updated on the "ast-cart-menu-wrap" icon after adding an item to the cart.
https://app.clickup.com/t/8689p8ya1
=> 2_14 | Store > Add item to my cart

src/test/java/BaseTest.java
Изменения согласованы с Алексом!)
=> Changed BaseTest

src/test/java/FirstTest.java
Objective: Verify the search functionality on the store web page.
Description:
Navigate to Store Page: Open the store web page at "https://askomdch.com/store/".
Enter Search Query: Type "Shoes" into the search field.
Initiate Search: Click the "Search" button to start the search.
Wait for Results: A 3-second delay is introduced to allow time for the search results to load.
Verify Results: Check that the search results header contains the word "Shoes".
Expected Result: The search results header should include the word "Shoes". If this is confirmed, the test is considered successful.
=> Search for a product. https://app.clickup.com/t/8689p8y0m

src/test/java/MyFirstTest.java
As a tester, 
I want to open the home page, scroll down to the footer and check,
if I click on each item in the quick links, corresponding page is opened.
=> add: test quick links from footer

src/test/java/FirstTest.java
https://app.clickup.com/t/8689p8y9v
=> add Accessories Add Item To Cart test

src/test/java/StorePage.java
https://app.clickup.com/t/8689p8y50
=> add store search test

src/test/java/StorePage.java
2.3_2.1 | Store > Search functionality for product> Negative Scenario – Searching for a Product That Is Not Available #
https://app.clickup.com/t/8689tnf46
=> added new test for search to StorePage

src/test/java/StorePage.java
https://app.clickup.com/t/8689p8y36
=> Added test 2_15 | Store > Go to the next page.

src/test/java/StorePage.java
1. 2.3-1.2.1 | TC > Store > Search functionality for product > Case Insensitivity > Uppercase Letters # https://app.clickup.com/t/8689u4rkc
2. 2.3-1.2.2 | TC > Store > Search functionality for product > Case Insensitivity > Lowercase Letters # https://app.clickup.com/t/8689u4zdd
3. 2.3-1.2.3 | TC > Store > Search functionality for product > Case Insensitivity > Combination of Uppercase and Lowercase Letters # https://app.clickup.com/t/8689u541z
=> added 3 test cases for Case Insensitivity

src/test/java/StorePage.java
https://app.clickup.com/t/8689p8y3y
TS : https://app.clickup.com/t/8689u8av6
=> add check prices test

src/test/java/StorePage.java
2.3-3 | TC > Store > Search functionality for product> Empty Search Field (Edge Case) # https://app.clickup.com/t/8689uckje
2.3-2.2 | TC > Store > Search functionality for product> Negative Scenario - Search with Special Characters # https://app.clickup.com/t/8689uev2u")
=> added test cases for Empty Search Field

src/test/java/CartTest.java, src/test/java/FirstTest.java
Refactor for a new CartTest class, and moved test to a new class.
9_1 | TC > Cart - Update the Cart - https://app.clickup.com/t/8689u7hd6
=> Refactor tests

src/test/java/FirstTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java
9_2 | TC > Cart - Remove single item from the cart - https://app.clickup.com/t/8689ucy2m
=> Refactor. Moved test to a new package

src/test/java/NavigationMenuTest.java
10.1 | RF >  Verify active page is highlighted in the navigation bar.   https://app.clickup.com/t/8689ufb6d
=> Refactor NavigationMenuTests

src/test/java/com/ecommerce/tests/components/footer/FooterAppstoresTest.java, src/test/java/com/ecommerce/tests/components/footer/FooterForHerTest.java, src/test/java/com/ecommerce/tests/components/footer/FooterForHimTest.java, src/test/java/com/ecommerce/tests/components/footer/FooterQuickLinksTest.java
=> refactor: structure

src/test/java/ItemTest.java
Also, add description to all tests
=> Add testVerifyReducedPriceForSaleItems

src/test/java/com/ecommerce/tests/components/footer/FooterQuickLinksTest.java
https://app.clickup.com/t/8689vptv7
=> add testQuickLinksHTTPS for Quick Links in footer

src/test/java/com/ecommerce/tests/store/StorePageTest.java
https://app.clickup.com/t/8689p8y50
=> add description to testSearchButton

src/test/java/com/ecommerce/tests/store/SortByPriceTest.java
2 - 1.0 TC> Store Page > Sort products by price from Low to High
=> SortByPrice

src/test/java/com/ecommerce/tests/components/left_sidemenu/LeftSideMenuTest.java
refactoring old tests, creating a new package LeftsideMenu and add refactoring test to it, adding ClickUp cards links
=> refactoring old tests, create new package LeftsideMenu

src/test/java/com/ecommerce/tests/components/left_sidemenu/LeftSideMenuTest.java
10.4-10.4-2  | TC >Search box Test> Search by key word> No product were found # https://app.clickup.com/t/8689xwcb5
10.2-10.2-2 | TC > Leftside_Bar > Browser by categories # https://app.clickup.com/t/8689x8my5
=> LeftSide Menu >Search box Test> Search by key word> No product  found

src/test/java/FirstTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java
9_6 | TC > Cart > Removing all items from the cart results in an empty cart state https://app.clickup.com/t/8689p8y04
=> Refactor. Test remove multiple items

src/test/java/com/ecommerce/tests/store/StorePageTest.java
2.3-2-3 | TC > Store > Search functionality for product> Negative Scenario - Search Error Handling | https://app.clickup.com/t/8689y3uy0
=> 2.3-2-3 | TC > Store > Search functionality for product

src/test/java/com/ecommerce/tests/store/StorePageTest.java
TC: https://app.clickup.com/t/8689yq16m
=> added check prices by browse by category on the Store page

src/test/java/com/ecommerce/tests/cart/CartTest.java
9  | RF > Refactor for tests - https://app.clickup.com/t/8689zdzc0
=> Refactor for tests

src/test/java/com/ecommerce/tests/components/footer/FooterAppstoresTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
-added numberOfWindowsWait with default timeout
-added numberOfWindowsWait with custom timeout
FooterAppstoresTest:
-refactored with new WaitUtils
=> WaitUtils:

src/test/java/com/ecommerce/tests/components/header/HeaderVisibleTest.java
Checking the placement of the header, the second attempt to make a pull request
=> Verify Header Placement #2

src/test/java/com/ecommerce/tests/components/header/NavigationMenuVisibleTest.java
Check that the main navigation menu is consistently visible at the top of all pages on the site, regardless of the page or section the user is on.
=> Verify Navigation Menu Placement.

src/test/java/com/ecommerce/tests/components/header/HeaderNavigationClickTest.java
Check that each of the header links (Home, Store, Men, Women, Accessories, Account, Contact Us, Cart) works correctly and redirects to the appropriate page
=> Verify Header Navigation

src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/ManPage.java, src/test/java/com/ecommerce/tests/men/MenTest.java, src/test/java/com/ecommerce/tests/store/StorePageTest.java
Refactor test to POM, delete data provider option from one of the tests
=> Refactor test to POM

src/test/java/com/ecommerce/tests/store/SeeItemsPicturesTest.java
Changed the wrong test name (visibilityOfImagesOnTheProductCartTest) to testVisibilityOfImagesOnTheProductCart
=> See items pictures refactor

src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/cart/CartTest.java
Refactor. Changing test using POM
=> Refactor. Changing test using POM

src/test/java/com/ecommerce/pom/BasePage.java
added header and footer navigation links data to BasePage
=> header and footer elements to base page

src/test/java/com/ecommerce/tests/account/RegisterTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
Add 3 tests and Wait , returtning Boolean. #3 test with comment "work in progress"
=> Add tests to RegisterTest

src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/WomenPage.java, src/test/java/com/ecommerce/tests/cart/AddProductFromWomenPageTest.java, src/test/java/com/ecommerce/uml/POM_Structure.puml
added  navigateToWomenPage() to class AccountPage
added class WomenPage 
added AddProductFromWomenPageTest
=> work in progress AddProductWomenPageTest

src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/store/StorePageTest.java
Also, one method was moved to page, did not delete from testclass since other tests still in progress and use it
=> Refactor to POM

src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByXTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByZeroTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
added class RemoveOneProductFromTheCartByXTest
added waitForQuantityToBe
=> work in progress RemoveOneProductFromTheCartByXTest

src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/pom/pages/CheckoutPage.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/java/com/ecommerce/tests/men/MenPageItemsOnSaleTest.java, src/test/java/com/ecommerce/tests/store/SortByPriceTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
https://app.clickup.com/t/868a6xuu8
=> refactoorendtoend

src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/cart/CartTest.java
=> fix: 9.1-3-3.1.1 test

src/test/java/com/ecommerce/tests/endtoend/EndToEndRegisteredUserTest.java
add EndToEndRegisteredUserTest
=> EndToEndRegisteredUserTest

src/test/java/com/ecommerce/tests/cart/CartTest.java
=> fix: 9.1-3-3.1.1 test rebase

src/test/java/com/ecommerce/tests/account/LoginBase.java, src/test/java/com/ecommerce/tests/account/RedirectionDashboardAfterLogin.java
=> add: 6.4-1-1 test

src/test/java/com/ecommerce/pom/pages/AccessoriesPage.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemsCategory.java
https://app.clickup.com/t/868a7t8vp
=> Accessory>VerifyItemsCategory

src/test/java/com/ecommerce/tests/accessories/VerifyItemIsOnSale.java
https://app.clickup.com/t/868a7y2ax
=> Accessory>VerifyItemIsOnSale

src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/tests/women/WomenAddToCartTest.java
https://app.clickup.com/t/8689p8yak
=> add testAddItemsToCart() from Women

src/test/java/com/ecommerce/pom/components/Header.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemIsOnSale.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemsCategory.java, src/test/java/com/ecommerce/tests/cart/CartTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/java/com/ecommerce/tests/men/MenPageItemsOnSaleTest.java, src/test/java/com/ecommerce/tests/men/MenTest.java, src/test/java/com/ecommerce/tests/store/SortByPriceTest.java, src/test/java/com/ecommerce/tests/store/StorePageTest.java, src/test/java/com/ecommerce/tests/women/WomenAddToCartTest.java
removed unused imports and methods, duplicate. Moved men/ women/ store to  header
=> Changes in header according lecture

src/test/java/com/ecommerce/pom/BasePage.java, src/test/java/com/ecommerce/pom/components/Footer.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemsCategory.java
footer was created;
methods and variables added to the footer
The BasePage is changed accordingly
A temporary test was added to the 'VerifyItemsCategory' class in the 'Accessories' package to test links in the Footer
=> footer was created;

src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/tests/components/header/NavigationMenuTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/java/com/ecommerce/tests/men/MenPageItemsOnSaleTest.java
https://app.clickup.com/t/868a6xuu8
=> onsaletest

src/test/java/com/ecommerce/pom/components/LeftSideMenu.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java
Add new component and make changes in tests accordingly
=> Add LeftSideMenu component

pom.xml, src/test/java/com/ecommerce/pom/pages/AccountOrdersPage.java, src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/tests/account/AccountPageOrderHistoryTest.java
https://app.clickup.com/t/868a9bufn
=> orderHistory

src/test/java/com/ecommerce/pom/pages/MenPage.java, src/test/java/com/ecommerce/tests/men/MenTest.java
added verifyHeaderText 3.7-1-1 |TC Only products categorized as "Men" should be displayed # https://app.clickup.com/t/868a7n2a8
=> verifyHeaderText

src/test/java/com/ecommerce/pom/Loadable.java, src/test/java/com/ecommerce/pom/pages/AccessoriesPage.java, src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/pom/pages/CheckoutPage.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/LostPasswordPage.java, src/test/java/com/ecommerce/pom/pages/MenPage.java, src/test/java/com/ecommerce/pom/pages/MensJeansPage.java, src/test/java/com/ecommerce/pom/pages/MensShirtsPage.java, src/test/java/com/ecommerce/pom/pages/MensShoesPage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/pom/pages/WomenPage.java, src/test/java/com/ecommerce/pom/pages/WomensJeansPage.java, src/test/java/com/ecommerce/pom/pages/WomensShirtsPage.java, src/test/java/com/ecommerce/pom/pages/WomensShoesPage.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemsCategory.java, src/test/java/com/ecommerce/tests/account/AccountPageOrderHistoryTest.java, src/test/java/com/ecommerce/tests/account/LostPasswordTest.java, src/test/java/com/ecommerce/tests/account/RegisterTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java, src/test/java/com/ecommerce/tests/men/MenPageItemsOnSaleTest.java, src/test/java/com/ecommerce/tests/men/MenTest.java
I updated the load() method to return a Page instead of void and made changes in the tests to use the load() method. Additionally, I deleted duplicate methods that can now be accessed from the header and made the necessary changes accordingly.
=> Make load method return Page instead void

pom.xml, src/test/java/com/ecommerce/pojo/User.java, src/test/java/com/ecommerce/tests/cart/AddProductAccessoriesTest.java, src/test/java/com/ecommerce/tests/cart/AddProductMenPageTest.java, src/test/java/com/ecommerce/tests/cart/AddProductStorePageTest.java, src/test/java/com/ecommerce/tests/cart/AddProductWomenPageTest.java, src/test/java/com/ecommerce/tests/cart/EmptyCartMessageTest.java, src/test/java/com/ecommerce/tests/cart/ItemsStayInTheCartTest.java, src/test/java/com/ecommerce/tests/cart/NavigateToCartUsingFooterMenuTest.java, src/test/java/com/ecommerce/tests/cart/NavigateToCartUsingHeaderMenuTest.java, src/test/java/com/ecommerce/tests/cart/NumberOfProductIsShownInTheIconTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByXTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByZeroTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromThePopUpByXTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/java/com/ecommerce/user.json, src/test/java/com/ecommerce/utils/UserUtils.java
=> jsonreader

src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/MenPage.java, src/test/java/com/ecommerce/pom/pages/PurchasePage.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java
productGrid 'added' to PurchasePage
Method clickAddToCartButton added to PurchasePage
Methods that override clickAddToCartButton added to HomePage, MenPage, WomanPage Mrthods tested in AddAnyProductToCartTest Class
=> PruductsGrid component class created

src/test/java/com/ecommerce/pom/components/LeftSidebar.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/tests/components/left_sidebar/LeftSidebarTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java
https://app.clickup.com/t/868abp8yn
Add testSearchWithTwoCharactersReturnsRelevantItems
Refactor to POM testVerifySearchReturnsAllItemsInAllCategories
=> Add test on Search output

src/test/java/com/ecommerce/pom/components/LeftSidebar.java, src/test/java/com/ecommerce/pom/pages/ProductPage.java, src/test/java/com/ecommerce/pom/pages/PurchasePage.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/tests/components/left_sidebar/LeftSidebarTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java
Made Search method return certain pages
=> Refactor Search method

src/test/java/com/ecommerce/pojo/User.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/resources/user1.json
1. Practice PR -> added new json file with User Data fields
2. Modified E2E Test with new json file
=> Added new json file with userr data

src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/AddressesPage.java, src/test/java/com/ecommerce/pom/pages/BillingAddressPage.java, src/test/java/com/ecommerce/tests/account/BillingAddressTest.java
https://app.clickup.com/t/868adye7r
=> add edit billing address test

src/test/java/com/ecommerce/pom/components/LeftSidebar.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/tests/components/left_sidebar/FilterByPriceTest.java, src/test/java/com/ecommerce/tests/components/left_sidebar/LeftSidebarTest.java
LeftSideBar Class:
getMinAvailableFilterPrice()
getMaxAvailableFilterPrice()
getDifferenceBetweenPriceFilterNods()
calculateOneStepXOffsetForPriceFilterSlider()
SalesPage Class:
moveLeftNodOfPriceFilter(int targetMinPrice)
moveRightNodOfPriceFilter(int targetMaxPrice)
FilterByPriceTest Class:
Mocktest added to test new methods
=> methods for manipulatinf 'Filter by Price' slider, and a mocktest to test the methods

src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/store/FindItemsOnSale.java, src/test/java/com/ecommerce/utils/UserUtils.java, src/test/java/com/ecommerce/utils/WaitUtils.java
=> add: 2.1-1-1 TC test

src/test/java/com/ecommerce/pom/components/Header.java, src/test/java/com/ecommerce/tests/components/header/NavigationMenuTest.java
https://app.clickup.com/t/8689yqyz1
=> refactor NavigationMenuTest

src/test/java/com/ecommerce/base/BaseTest.java, src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/tests/account/RegisteredUserLoginTest.java, src/test/java/com/ecommerce/tests/cart/AddProductAccessoriesTest.java, src/test/java/com/ecommerce/tests/cart/AddProductMenPageTest.java, src/test/java/com/ecommerce/tests/cart/AddProductStorePageTest.java, src/test/java/com/ecommerce/tests/cart/AddProductWomenPageTest.java, src/test/java/com/ecommerce/tests/cart/EmptyCartMessageTest.java, src/test/java/com/ecommerce/tests/cart/ItemsStayInTheCartTest.java, src/test/java/com/ecommerce/tests/cart/NumberOfProductIsShownInTheIconTest.java, src/test/java/com/ecommerce/tests/cart/RemoveAllItemsFromCartTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByXTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromThePopUpByXTest.java
rename clearCartFromAllItems() to clearCart()
delete comments in AccountPage
delete clearCartFromAllItems1 from CartPage (it was a duplicate method)
=> rename logOutFromMainContent() to logOutUser()

src/test/java/com/ecommerce/pom/pages/AccessoriesPage.java, src/test/java/com/ecommerce/pom/pages/AccountPage.java, src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/pom/pages/PurchasePage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/pom/pages/WomenPage.java, src/test/java/com/ecommerce/tests/about/AboutUsNavigationTest.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemIsOnSaleTest.java, src/test/java/com/ecommerce/tests/accessories/VerifyItemsCategoryTest.java, src/test/java/com/ecommerce/tests/cart/AddProductAccessoriesTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java, src/test/java/com/ecommerce/tests/home/AddAnyProductToCartTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
https://app.clickup.com/t/868ahqneh
https://app.clickup.com/t/868aje1tf
https://app.clickup.com/t/868ajee4j
=> Cart test refactoring

src/test/java/com/ecommerce/pom/BaseModel.java, src/test/java/com/ecommerce/pom/components/Header.java, src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/cart/AddProductStorePageTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java, src/test/java/com/ecommerce/tests/components/header/HeaderNavigationMenuVisibleTest.java, src/test/java/com/ecommerce/tests/women/WomenAddToCartTest.java, src/test/java/com/ecommerce/utils/WaitUtils.java
1. "Header" methods removed from the HomePageClass (the same methods were already created in the "Header" class)
2. Test 9.1-3-3.4 is refactored (now it is 9.1-3.4)
3. Test 9.1-2-2.3 is refactored (now it is 9.1-2.3)
=> Cart tests refacror

src/test/java/com/ecommerce/pom/components/Header.java, src/test/java/com/ecommerce/pom/pages/CartPage.java, src/test/java/com/ecommerce/pom/pages/HomePage.java, src/test/java/com/ecommerce/pom/pages/MenPage.java, src/test/java/com/ecommerce/pom/pages/MensJeansPage.java, src/test/java/com/ecommerce/pom/pages/MensShirtsPage.java, src/test/java/com/ecommerce/pom/pages/MensShoesPage.java, src/test/java/com/ecommerce/pom/pages/PurchasePage.java, src/test/java/com/ecommerce/pom/pages/SalesPage.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/pom/pages/WomenPage.java, src/test/java/com/ecommerce/pom/pages/WomensJeansPage.java, src/test/java/com/ecommerce/pom/pages/WomensShirtsPage.java, src/test/java/com/ecommerce/pom/pages/WomensShoesPage.java, src/test/java/com/ecommerce/tests/cart/AddProductMenPageTest.java, src/test/java/com/ecommerce/tests/cart/AddProductWomenPageTest.java, src/test/java/com/ecommerce/tests/cart/CartTest.java, src/test/java/com/ecommerce/tests/cart/ItemsStayInTheCartTest.java, src/test/java/com/ecommerce/tests/cart/NumberOfProductIsShownInTheIconTest.java, src/test/java/com/ecommerce/tests/cart/RemoveAllItemsFromCartTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByXTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromTheCartByZeroTest.java, src/test/java/com/ecommerce/tests/cart/RemoveOneProductFromThePopUpByXTest.java, src/test/java/com/ecommerce/tests/endtoend/EndToEndTest.java, src/test/java/com/ecommerce/tests/women/WomenAddToCartTest.java
Some of the methods and elements belonging to 'Header' and 'ProductGrid' components are removed from "Page" classes. Tests that use them refactored accordingly.
=> Redundant "add to cart" and some other methods deleted

src/test/java/com/ecommerce/pom/components/LeftSidebar.java, src/test/java/com/ecommerce/tests/women/WomenBrowseByCategoriesTest.java
https://app.clickup.com/t/8689p8y7j
=> add testDefaultBrowseByCategoriesText()

src/test/java/com/ecommerce/pom/pages/WomenPage.java, src/test/java/com/ecommerce/tests/women/WomenProductImageTest.java, src/test/java/com/ecommerce/utils/JSExecutorUtils.java
https://app.clickup.com/t/8689p8y3b
=> add testProductImage()

src/test/java/com/ecommerce/data/LeftSideBarWomenData.java, src/test/java/com/ecommerce/tests/women/WomenSearchTest.java
https://app.clickup.com/t/8689p8y60
=> add test search field with data provider

src/test/java/com/ecommerce/pom/pages/AboutPage.java, src/test/java/com/ecommerce/tests/about/AboutUsOurTeamTest.java
https://app.clickup.com/t/868antxxf
=> add AboutPage add testOurTeamImage()

src/test/java/com/ecommerce/data/Product.java, src/test/java/com/ecommerce/pom/components/ProductsGrid.java, src/test/java/com/ecommerce/pom/pages/StorePage.java, src/test/java/com/ecommerce/tests/store/SortByPriceTest.java
1) Test 'Sort all products in the shop by price from high to low using 'Product' object' is added
https://app.clickup.com/t/868ar73c2
2) Test 2 - 1.1 Sort products by price from High to Low is refactored
3) Test 2 - 1.0 Sort products by price from Low to high is refactored
=> Sort by price tests
